services:
  telegram-bot:
    build: .
    container_name: tg-file-store-bot
    restart: always
    environment:
      - BOT_TOKEN=88000009:AA
      - ADMIN_USER_ID=59
      - DB_CHANNEL_ID=-100    # <--- 填入你自己的存储频道ID（带-100前缀）
      - FORCE_SUB_CHANNEL_ID=-100
      - FORCE_SUB_INVITE_LINK=https://
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
